export const level1= [
  {
    id:1,
    image:"https://AyaHA20.github.io/Memory-card-game/img/img1.jpg",
  },
  {
    id:2,
    image:"https://AyaHA20.github.io/Memory-card-game/img/img2.jpg",
  },
  {
    id:3,
    image:"https://AyaHA20.github.io/Memory-card-game/img/img3.jpg",
  },
  {
    id:4,
    image:"https://AyaHA20.github.io/Memory-card-game/img/img4.jpg",
  },
  {
    id:5,
    image:"https://AyaHA20.github.io/Memory-card-game/img/img5.jpg",
  },
  {
    id:6,
    image:"https://AyaHA20.github.io/Memory-card-game/img/img6.jpg",
  },
  {
    id:7,
    image:"https://AyaHA20.github.io/Memory-card-game/img/img7.jpg",
  },
  {
    id:8,
    image:"https://AyaHA20.github.io/Memory-card-game/img/img8.jpg",
  }
]
export const level2=[
  {
    id:9,
    image:"https://AyaHA20.github.io/Memory-card-game/img/img9.jpg",
  },
  {
    id:10,
    image:"https://AyaHA20.github.io/Memory-card-game/img/img10.jpg",
  },
  {
    id:11,
    image:"https://AyaHA20.github.io/Memory-card-game/img/img11.jpg",
  },
  {
    id:12,
    image:"https://AyaHA20.github.io/Memory-card-game/img/img12.jpg",
  },
  {
    id:13,
    image:"https://AyaHA20.github.io/Memory-card-game/img/img13.jpg",
  },
  {
    id:14,
    image:"https://AyaHA20.github.io/Memory-card-game/img/img14.jpg",
  },
  {
    id:15,
    image:"https://AyaHA20.github.io/Memory-card-game/img/img15.jpg",
  },
  {
    id:16,
    image:"https://AyaHA20.github.io/Memory-card-game/img/img16.jpg",
  },
  {
    id:17,
    image:"https://AyaHA20.github.io/Memory-card-game/img/img17.jpg",
  },
  {
    id:18,
    image:"https://AyaHA20.github.io/Memory-card-game/img/img18.jpg",
  },
  {
    id:19,
    image:"https://AyaHA20.github.io/Memory-card-game/img/img19.jpg",
  },
  {
    id:20,
    image:"https://AyaHA20.github.io/Memory-card-game/img/img20.jpg",
  }
]
export const level3=[
  {
    id:21,
    image:"https://AyaHA20.github.io/Memory-card-game/img/img21.jpg",
  },
  {
    id:22,
    image:"https://AyaHA20.github.io/Memory-card-game/img/img22.jpg",
  },
  {
    id:23,
    image:"https://AyaHA20.github.io/Memory-card-game/img/img23.jpg",
  },
  {
    id:24,
    image:"https://AyaHA20.github.io/Memory-card-game/img/img24.jpg",
  },
  {
    id:25,
    image:"https://AyaHA20.github.io/Memory-card-game/img/img25.jpg",
  },
  {
    id:26,
    image:"https://AyaHA20.github.io/Memory-card-game/img/img26.jpg",
  },
  {
    id:27,
    image:"https://AyaHA20.github.io/Memory-card-game/img/img27.jpg",
  },
  {
    id:28,
    image:"https://AyaHA20.github.io/Memory-card-game/img/img28.jpg",
  },
  {
    id:29,
    image:"https://AyaHA20.github.io/Memory-card-game/img/img29.jpg",
  },
  {
    id:30,
    image:"https://AyaHA20.github.io/Memory-card-game/img/img30.jpg",
  },
  {
    id:31,
    image:"https://AyaHA20.github.io/Memory-card-game/img/img31.jpg",
  },
  {
    id:32,
    image:"https://AyaHA20.github.io/Memory-card-game/img/img32.jpg",
  },
  {
    id:33,
    image:"https://AyaHA20.github.io/Memory-card-game/img/img33.jpg",
  },
  {
    id:34,
    image:"https://AyaHA20.github.io/Memory-card-game/img/img34.jpg",
  },
  {
    id:35,
    image:"https://AyaHA20.github.io/Memory-card-game/img/img35.jpg",
  },
  {
    id:36,
    image:"https://AyaHA20.github.io/Memory-card-game/img/img36.jpg",
  },
  {
    id:37,
    image:"https://AyaHA20.github.io/Memory-card-game/img/img37.jpg",
  },
  {
    id:38,
    image:"https://AyaHA20.github.io/Memory-card-game/img/img38.jpg",
  },
]
